// Wire types for the daemon's HTTP + queue surface.
// Mirrors @aylith/inspekt-core's InspectedElement subset that's safe to serialize —
// no DOM nodes, no DOMRects, no functions. Snippets travel along when
// available; the agent sees the actual source instead of just `file:line:col`.

export interface SerializedSnippet {
  startLine: number;
  endLine: number;
  targetLine: number;
  lines: string[];
  language: string;
  source: 'devserver' | 'sourcemap' | 'fiber';
}

export interface SerializedElement {
  filePath: string;
  line: number;
  column: number;
  componentName: string;
  tagName: string;
  classList: string[];
  id: string | null;
  rect?: { x: number; y: number; width: number; height: number };
  snippet?: SerializedSnippet;
}

export interface Grab {
  /** ULID — sortable by insertion time. */
  id: string;
  /** Unix-millis when the grab was captured by the extension. */
  timestamp: number;
  /** Page URL the grab came from. */
  url: string;
  /** Element details (the user-visible target). */
  element: SerializedElement;
  /** Optional user-typed note. */
  comment?: string;
  /** Optional captured computed styles (CSS string). */
  styles?: string;
  /** Identifier of the producing side. */
  source: 'extension' | 'cli';
  /** Set when an agent has consumed the grab via mark_grab_processed. */
  processedAt?: number;
}

export interface DaemonConfig {
  /** Token required in `X-Inspekt-Token` header. Generated by `inspekt setup`. */
  token: string;
  /** Bind address (default 127.0.0.1). */
  host: string;
  /** Bind port (default 5678 — matches @code-inspector/core's DefaultPort). */
  port: number;
  /** Path to the queue NDJSON file. */
  queuePath: string;
}
